spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: kaysen
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10